name: Delete logs for Windows service older than 20 minutes on scheduled basis

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 */5 * * *'
  #  - cron: '0 0 * * *'
  #  - cron: '0 */5 * * *'
  

jobs:
  delete-logs:
    runs-on: [self-hosted, Windows, X64, "windows-service-demo-passive"]
    environment: production
    defaults:
      run:
        shell: cmd
    env:
     LOG_PATH: ${{ vars.LOG_PATH }}
  
    steps:
      - name: Delete service logs older than two hours
        shell: powershell
        run: |
          $logsPath = "${{ env.LOG_PATH }}\"
          $cutoffDate = (Get-Date).AddMinutes(-20)
          Get-ChildItem -Path $logsPath -Recurse | Where-Object { $_.LastWriteTime -lt $cutoffDate } | ForEach-Object { Write-Host "Deleting log: $_"; Remove-Item -Path $_.FullName -Force -Recurse } 
          echo "Logs are deleted successfully"
